include:
    - docker-compose-ranger.yml

services:
    trino:
        image: trinodb/trino:latest
        container_name: trino
        hostname: trino
        volumes:
            - ../certs:/home/docker-certificates
            - ./trino:/etc/trino
        environment:
            CATALOG_MANAGEMENT: dynamic
        ports:
            - 8084:80
            - 44384:443
        networks:
            - trino-network
            - ranger-network

networks:
    trino-network:
