# include:
#     - docker-compose-ranger.yml

services:
    trino:
        image: trinodb/trino:latest
        container_name: trino
        hostname: trino
        volumes:
            - ./trino:/etc/trino
            - ../certs:/home/docker-certificates/
        environment:
            CATALOG_MANAGEMENT: dynamic
        ports:
            - 8084:80
            - 8443:443
        networks:
            - trino-network

networks:
    trino-network:
