include:
    - docker-compose-ranger.yml

services:
    trino:
        image: trinodb/trino:latest
        container_name: trino
        hostname: trino
        volumes:
            - ./trino:/etc/trino
        environment:
            CATALOG_MANAGEMENT: dynamic
        ports:
            - 8084:443
        depends_on:
            - ranger
        networks:
            - trino-network
            - ranger-network

networks:
    trino-network:
